name: alexa-web-dev
services:
  app:
    container_name: alexa-web-dev
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ../../src:/app
      - /app/.next
      - /app/node_modules
    env_file:
      - ../../src/.env.local
      - ../../src/.env.example
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_YANDEX_MAPS_API_KEY=${NEXT_PUBLIC_YANDEX_MAPS_API_KEY:-}
    restart: unless-stopped
